global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "scraper"
    static_configs:
      - targets: ["scraper-service:2114"]

  - job_name: "consumer"
    static_configs:
      - targets: ["consumer-service:2113"]
